import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pathlib
from typing import Union


class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """
    
    def __init__(self, data_fname: Union[pathlib.Path, str]):
        self.file_name = data_fname
        self.data = self.read_data()

    def read_data(self):
        """
        Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        return pd.read_json(self.file_name)

    def show_age_distrib(self):
        """
        Calculates and plots the age distribution of the participants.
        Returns a tuple containing two numpy arrays:
        The first item being the number of people in a given bin.
        The second item being the bin edges.
        """
        ages = self.data['age'][~self.data['age'].isna()]
        [hist, bins] = np.histogram(ages, range=(0, 100))
        fig = plt.figure(figsize=(10, 10))
        plt.hist(ages, bins=bins)
        plt.show()
        return hist, bins

    def remove_rows_without_mail(self) -> pd.DataFrame:
        """
        Checks self.data for rows with invalid emails, and removes them.
        Returns the corrected DataFrame, i.e. the same table but with
        the erroneous rows removed and the (ordinal) index after a reset.
        """



if __name__ == '__main__':
    qa = QuestionnaireAnalysis('data.json')
    print(qa.show_age_distrib())